# Enable the nice view OLED display
CONFIG_ZMK_DISPLAY=y
# CONFIG_SHIELD_NICE_VIEW=y
# Not user configurable?
# CONFIG_DT_HAS_RASPBERRYPI_PICO_USBD_ENABLED=y
# CONFIG_USB_DC_RPI_PICO=y
# I think this tries to show battery and bluetooth. I have neither
CONFIG_NICE_VIEW_WIDGET_STATUS=n
# CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y
# CONFIG_ZMK_LV_FONT_DEFAULT_SMALL_MONTSERRAT_26=y
# CONFIG_LV_FONT_DEFAULT_MONTSERRAT_26=y

# Enable the RGB LED on the mcu
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y
# Might need this? It's in the ws2812 pio Kconfig
# CONFIG_WS2812_STRIP_RPI_PICO_PIO=y
